<img width="300px" src="https://cachimbo.pe/wp-content/uploads/2022/10/1-19.jpg"></img>

#**Matemática y Estadística para Ciencia de Datos**
## **Tema: Introducción a python**
#### **Docente: Giron Rene Omar A.**

---------------


**Índice**   
1. [Variables y tipo de datos](#id1)
2. [Estructuras condicionales y Bucles](#id2)
3. [Funciones](#id3)<br>
4. [Numpy](#id4)<br>
5. [Pandas](#id5) <br>
6. [Scipy](#id6) <br>
6. [Matplotlib](#id7) <br>

<a name="id1"></a> <h2>Variables y Tipos de Datos </h2>
##  

* En Python, puedes asignar valores a variables.
* Python determinará automáticamente el tipo de datos.
* Python admite una variedad de estructuras y tipos de datos:
    * booleans (True or False)
    * numbers (ints, floats, etc.)
    * strings
    * lists
    * dictionaries
    * y muchos más!

In [2]:
print("¡Hola Mundo!")

¡Hola Mundo!


In [3]:
es_estudiante = True
print(es_estudiante)
type(es_estudiante)

True


bool

In [4]:
edad = 30
altura = 1.75

print('Edad: ',edad,'| Tipo de dato: ',type(edad))
print('Altura: ',edad,'| Tipo de dato: ',type(altura))

Edad:  30 | Tipo de dato:  <class 'int'>
Altura:  30 | Tipo de dato:  <class 'float'>


In [5]:
nombre = "Juan"
print(nombre)

Juan


In [6]:
lista = [1,2,3]
print(lista)

lista = ['b',2,'a']
print(lista)

lista = ['b','hola','mundo']
print(lista)

lista = [None,'hola','mundo']
print(lista)

[1, 2, 3]
['b', 2, 'a']
['b', 'hola', 'mundo']
[None, 'hola', 'mundo']


In [7]:
diccionario = {'clave':'valor','omar':'giron','universidad':'ricado palma'}
diccionario

{'clave': 'valor', 'omar': 'giron', 'universidad': 'ricado palma'}

In [8]:
diccionario.keys()

dict_keys(['clave', 'omar', 'universidad'])

In [9]:
diccionario.values()

dict_values(['valor', 'giron', 'ricado palma'])

<a name="id2"></a> <h2>Estructura condicionale y Bucles </h2>
##  

### Estructura condicional simple y compuesta
Una sentencia condicional consiste básicamente en las siguientes partes principales:

- una prueba que evalúa a verdadero o falso
- un bloque de código que se ejecuta si la prueba es verdadero
- un bloque opcional de código si la prueba es falsa

In [10]:
# Estructura condicional simple
x = 10
if x > 0:
    print("x es positivo")
else:
    print("x es negativo")

x es positivo


In [11]:
# Estructura condicional compuesta
x = 0
if x > 0:
    print("x es positivo")
elif x == 0:
    print("x es cero")
else:
    print("x es negativo")

x es cero


### Bucles

Los bucles son una estructura fundamental en la programación, que nos permiten ejecutar un bloque de código repetidamente mientras se cumple una condición. En Python, existen dos tipos de bucles: "for" y "while".

In [12]:
# Bucle for
for i in range(5):
    print(i)

0
1
2
3
4


In [13]:
# Bucle while
contador = 0
while contador < 5:
    print(contador)
    contador += 1

0
1
2
3
4


<a name="id3"></a> <h2>Funciones </h2>
##  

En Python, puedes definir tus propias funciones utilizando la palabra clave def.

In [14]:
def suma(a, b):
    return a + b

resultado = suma(3, 5)
print(resultado)  # Salida: 8

8


In [15]:
def hello(name, loud=False):
    if loud:
        print('HELLO, {}'.format(name.upper()))
    else:
        print('Hello, {}!'.format(name))

hello('Bob')
hello('Fred', loud=True)

Hello, Bob!
HELLO, FRED


<a name="id4"></a> <h2>Numpy </h2>
##  

Numpy es la biblioteca central para informática científica en Python. Proporciona un objeto de matriz multidimensional de alto rendimiento y herramientas para trabajar con estas matrices.

In [16]:
import numpy as np

### Array
Es una cuadrícula de valores, todos del mismo tipo, y está indexada por una tupla de números enteros no negativos. El número de dimensiones es el rango de la matriz; la forma de una matriz es una tupla de números enteros que indican el tamaño de la matriz en cada dimensión.

In [17]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])

<class 'numpy.ndarray'>
(3,)
1 2 3


In [18]:
a[0] = 5                 # Change an element of the array
print(a)

[5 2 3]


In [19]:
np.array([-1, -2, -3])

array([-1, -2, -3])

In [20]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [21]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [23]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [24]:
b = np.ones((2,1))   # Create an array of all ones
print(b)

[[1.]
 [1.]]


In [25]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [26]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.27173542 0.07888024]
 [0.10399035 0.89576426]]


### Array index
Numpy ofrece varias formas de indexar matrices.

División: similar a las listas de Python, se pueden dividir numerosas matrices. Dado que las matrices pueden ser multidimensionales, debe especificar una porción para cada dimensión de la matriz:

In [27]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


<a name="id5"></a> <h2>Pandas </h2>
##  

Pandas proporciona dos estructuras de datos principales: DataFrame para datos tabulares y Series para datos unidimensionales.




In [29]:
import pandas as pd

In [30]:
# Puedes crear un DataFrame de Pandas a partir de un diccionario de Python:

# Crear un DataFrame de Pandas
data = {'Nombre': ['Juan', 'María', 'Carlos', 'Ana'],
        'Edad': [25, 30, 35, 40],
        'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla']}

df = pd.DataFrame(data)
df


Nombre  Edad     Ciudad
0    Juan    25     Madrid
1   María    30  Barcelona
2  Carlos    35   Valencia
3     Ana    40    Sevilla

In [31]:
# Acceder a una columna específica
nombres = df['Nombre']
nombres

0      Juan
1     María
2    Carlos
3       Ana
Name: Nombre, dtype: object

In [32]:
# Acceder a una fila específica
fila = df.iloc[0]
fila

Nombre      Juan
Edad          25
Ciudad    Madrid
Name: 0, dtype: object

In [34]:
data = pd.read_csv(r'C:\Users\dg_su\OneDrive - Universidad Tecnologica del Peru\Estudios\Cursos\Analisis de Datos\Universidad Ricardo Palma\MATEMÁTICA Y ESTADÍSTICA EN CIENCIA DE DATOS\codigo\base de datos\california_housing_test.csv')
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

<a name="id6"></a> <h2>SciPy </h2>
##  

Scipy es una biblioteca de Python de código abierto que se utiliza para realizar operaciones matemáticas, científicas y de ingeniería. Proporciona una amplia gama de funcionalidades para realizar cálculos numéricos eficientes, manipulación de datos, optimización, álgebra lineal, estadísticas y más.

 Operaciones de Álgebra Lineal

In [ ]:
import numpy as np
from scipy.linalg import solve, qr

# Crear una matriz A y un vector b
A = np.array([[2, 1], [1, 3]])
b = np.array([4, 5])

# Resolver el sistema de ecuaciones lineales Ax = b
x = solve(A, b)
print("Solución del sistema de ecuaciones lineales:", x)

Optimización Numérica

In [ ]:
from scipy.optimize import minimize

# Definir una función objetivo
def objetivo(x):
    return (x[0] - 1)**2 + (x[1] - 2)**2

# Realizar la minimización de la función objetivo
resultado = minimize(objetivo, [0, 0])
print("Mínimo de la función:", resultado.x)

 Integración Numérica

In [ ]:
from scipy.integrate import quad

# Definir una función a integrar
def f(x):
    return np.exp(-x**2)

# Realizar la integración numérica de la función
resultado, error = quad(f, 0, np.inf)
print("Resultado de la integración:", resultado)
print("Error estimado:", error)

Estadísticas

In [ ]:
from scipy.stats import norm

# Generar números aleatorios distribuidos normalmente
datos_aleatorios = norm.rvs(loc=0, scale=1, size=1000)
print("Datos aleatorios distribuidos normalmente:")
print(datos_aleatorios[:10])  # Mostrar los primeros 10 datos

<a name="id7"></a> <h2>Matplotlib </h2>
##  

Matplotlib es una biblioteca de visualización de datos en Python que permite crear gráficos de alta calidad y personalizables. En este tutorial, aprenderás cómo utilizar Matplotlib para crear diferentes tipos de gráficos, como gráficos de líneas, de dispersión, de barras, entre otros.

In [ ]:
import matplotlib.pyplot as plt

 Gráfico de Líneas

In [ ]:
# Datos
x = [1, 2, 3, 4, 5]
y = [2, 3, 5, 7, 11]

# Crear gráfico de líneas
plt.plot(x, y)

# Mostrar gráfico
plt.show()

Gráfico de Dispersión

In [ ]:
# Datos
x = [1, 2, 3, 4, 5]
y = [2, 3, 5, 7, 11]

# Crear gráfico de dispersión
plt.scatter(x, y)

# Mostrar gráfico
plt.show()


Gráfico de Barras

In [ ]:
# Datos
x = ['A', 'B', 'C', 'D', 'E']
y = [20, 35, 30, 25, 40]

# Crear gráfico de barras
plt.bar(x, y)

# Mostrar gráfico
plt.show()

Personalización de Gráficos

In [ ]:
# Datos
x = [1, 2, 3, 4, 5]
y1 = [2, 3, 5, 7, 11]
y2 = [1, 4, 9, 16, 25]

# Crear gráfico de líneas con personalización
plt.plot(x, y1, label='Primos', color='blue', linestyle='--', marker='o')
plt.plot(x, y2, label='Cuadrados', color='red', linestyle='-', marker='x')

# Añadir etiquetas y leyenda
plt.xlabel('X')
plt.ylabel('Y')
plt.title('Gráfico de Líneas')
plt.legend()

# Mostrar cuadrícula
plt.grid(True)

# Mostrar gráfico
plt.show()
